### ISSUE TITLE
JEI Recipe Spam

### ISSUE THREAD

**Issue by Tetrajak** [the-realest-stu/Rustic#143] opened 2018-02-17 00:16 UTC
Minecraft Version: 1.12.2
Forge Build: 2611
JEI Version: 4.8.5.151 (and 4.8.5.147)
Mod Version: 0.4.8

Many recipes in JEI are duplicated, which is especially noticeable with wood planks. Some of these recipes are the regular minecraft ones, but there are quite a few that JEI attributes to Rustic. I assume this is due to the mod adding recipes for wooden items out of olive and iron wood. Shouldn't these items be made valid ingredients for the relevant recipes if they're simply added to the correct oredict entries, thus removing the necessity of adding new recipes to achieve the same effect?

**Comment by the-realest-stu** [comment] 2018-02-24 07:45
Duplicate of issue #136

**Closed by the-realest-stu** 2018-02-24 07:45 UTC
