### ISSUE TITLE
some of the mod's blocks'  arent showing the light levels properly

### ISSUE THREAD

**Issue by majijn** [the-realest-stu/Rustic#116] opened 2017-12-11 08:19 UTC
![2017-12-10_11 14 36](https://user-images.githubusercontent.com/18368034/33821491-47bf1b30-de54-11e7-9eda-c0ad30172df5.png)
i noticed that ironwood stairs have this issue as well. havent gotten around to checking other blocks in the mod.

**Comment by the-realest-stu** [comment] 2017-12-28 13:35
I can't seem to reproduce this. Do you have any more information you could provide?

**Comment by Lorelando** [comment] 2018-02-16 22:32
This might be caused by Optifine. Do you have it installed?  #142

**Comment by the-realest-stu** [comment] 2018-02-25 13:47
This does in fact seem to be caused by optifine. I'll see if this happens with other mods' stairs and stuff, and see if anyone else has found a solution for this.

**Comment by the-realest-stu** [comment] 2018-02-25 14:23
I managed to find a fix for this. I plan on releasing an update with this fix and more later today.

**Comment by the-realest-stu** [comment] 2018-02-25 18:19
The update has been released.

**Closed by the-realest-stu** 2018-02-25 18:19 UTC
