### ISSUE TITLE
Wooden tool recipes causing incompatibilities

### ISSUE THREAD

**Issue by NotAVerb** [the-realest-stu/Rustic#147] opened 2018-02-21 07:46 UTC
Rustic adds recipes for the wooden toolset that accept "any stick" and "any plankWood".
These recipes mess up tool recipes using variant woods, such as Natura and Betweenlands tools.

If the recipes didn't accept "any plankWood" and instead only used olive and ironwood planks the problem should go away, I hope.

**Comment by the-realest-stu** [comment] 2018-02-24 07:45
Duplicate of issue #136

**Closed by the-realest-stu** 2018-02-24 07:45 UTC
