### ISSUE TITLE
Rustic's honey has no texture!

### ISSUE THREAD

**Issue by Sunconure11** [the-realest-stu/Rustic#102] opened 2017-11-02 22:13 UTC
![screenshot 2017-11-02 18 12 35](https://user-images.githubusercontent.com/5614902/32352907-8e3a9090-bff9-11e7-86b4-963b77c3b36b.png)

**Comment by the-realest-stu** [comment] 2018-02-25 12:19
Closing this since I can't reproduce it and no one else has reported this in the time since the issue was opened.

**Closed by the-realest-stu** 2018-02-25 12:19 UTC

**Comment by Voxel-Friend** [comment] 2018-04-26 00:06
I have this issue. Modlist: https://gist.github.com/Voxel-Friend/c06aeb5656b30fe4aa08ca976663bdd9

I would really Like to get to the bottom of this.

**Comment by Voxel-Friend** [comment] 2018-04-26 02:00
@the-realest-stu
